skhualumni/alumni/urls.py
from django.conf.urls import url
from alumni.views import UserLV, ExecutiveLV, UserDV

urlpatterns = [
    url(r'^$', UserLV.as_view(), name='index'),
    url(r'^executive/$', ExecutiveLV.as_view(), name='executive'),
    url(r'^(?P<pk>\d+)/$', UserDV.as_view(), name='detail'),
]

skhualumni/board/urls.py
# coding=utf-8
from django.conf.urls import url
from board.views import *

urlpatterns = [
    url(r'^$', index, name='index'),    # 글 목록
    url(r'^(?P<pk>\d+)/$', post_detail, name='post_detail'),    # 글 내용
    url(r'^(?P<pk>\d+)/edit/$', post_edit, name='post_edit'),   # 글 수정
    url(r'^new/$', post_new, name='post_new'),     # 새 글 등록
    url(r'^search/$', PostSearch.as_view(), name='post_search'),  # 글 검색
    url(r'^(?P<pk>\d+)/delete/$', post_delete, name='post_delete'),  # 글 삭제
    url(r'^(?P<pk>\d+)/comments/new/$', comment_new, name='comment_new'),    # 댓글 작성
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/edit/$', comment_edit, name='comment_edit'),     # 댓글 수정
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/delete/$', comment_delete, name='comment_delete'),  # 댓글 삭제
]

skhualumni/info/urls.py
from django.conf.urls import url
from info.views import *

urlpatterns = [
    url(r'^$', render_greeting, name='index'),
    url(r'^greeting/$', render_greeting, name='greeting'),
    url(r'^business/$', render_business, name='business'),
    url(r'^organization/$', render_organization, name='organization'),
    url(r'^map/$', render_map, name='map'),
    url(r'^usage/$', render_usage, name='usage'),
]

skhualumni/skhualumni/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from skhualumni.views import HomeView, UserUpdateView
from skhualumni.forms import CustomPasswordChangeForm
from django.contrib.auth.views import password_change

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    # login, logout, password_change
    url(r'^password_change/$', password_change,
        {'password_change_form': CustomPasswordChangeForm}, name="password_change"),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^my_page/$', UserUpdateView.as_view(), name='my_page'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'^notice/', include('notice.urls', namespace='notice')),
    url(r'^alumni/', include('alumni.urls', namespace='alumni')),
    url(r'^info/', include('info.urls', namespace='info')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skhualumni/templates/_sub_menu.html
{# templates/_sub_menu.html #}
{% comment %}
    Usage: {% include "_sub_menu.html" %}
{% endcomment %}
{% if "/info/" in request.path %}
<div class="tab2">
    <ul class="nav navbar-nav navbar-collapse">
        <li><a href="{% url 'info:greeting' %}">인 사 말</a></li>
        <li><a href="{% url 'info:business' %}">사업안내</a></li>
        <li><a href="{% url 'info:organization' %}">조직안내</a></li>
        <li><a href="{% url 'info:map' %}">오시는길</a></li>
        <li><a href="{% url 'info:usage' %}">이용안내</a></li>
    </ul>
</div>

{% elif "/board/" in request.path %}
    <div class="tab2">
        <ul class="nav navbar-nav navbar-collapse">
            <li><a href="{% url 'notice:index' %}">공지사항</a></li>
            <li><a href="{% url 'board:index' %}">자유게시판</a></li>
        </ul>
    </div>

{% elif "/notice/" in request.path %}
    <div class="tab2">
        <ul class="nav navbar-nav navbar-collapse">
            <li><a href="{% url 'notice:index' %}">공지사항</a></li>
            <li><a href="{% url 'board:index' %}">자유게시판</a></li>
        </ul>
    </div>

{% elif "/alumni/" in request.path %}
    <div class="tab2">
        <ul class="nav navbar-nav navbar-collapse">
            <li><a href="{% url 'alumni:index' %}">동문목록</a></li>
            <li><a href="{% url 'alumni:executive' %}">임원목록</a></li>
        </ul>
    </div>
{% else %}
<!--
    <div class="tab2">
        <ul class="nav navbar-nav navbar-collapse">
            <li><a href="#">이용안내</a></li>
            <li><a href="#">사이트맵</a></li>
        </ul>
    </div>
-->
{% endif %}

skhualumni/templates/base.html
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}SKHU 동문회 사이트{% endblock %}</title>

    {% load staticfiles %}
    <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://pingendo.github.io/pingendo-bootstrap/themes/default/bootstrap.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="/static/css/base.css"/>
    <link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}"/>

</head>
<body>
{% block header %}
    <header>
        <div class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url "home" %}"><span>성공회대학교 인문학습원</span></a>
                </div>
                <div class="collapse navbar-collapse" id="navbar-ex-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url 'info:index' %}">기관소개</a></li>
                        {% if user.is_active %}
                            <li><a href="{% url 'notice:index' %}">열림마당</a></li>
                            <li><a href="{% url 'alumni:index' %}">동문회</a></li>
                            <li><a href="{% url 'my_page' %}">마이페이지</a></li>
                            <li><a href="{% url 'logout' %}">Logout</a></li>
                            {% if user.is_admin %}
                                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                            {% endif %}
                        {% else %}
                            <li><a href="#">기타서비스</a></li>
                            <li><a href="{% url 'login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </header>
{% endblock %}

    <div class="content">
{% block submenu %}
    {% include "_sub_menu.html" %}
{% endblock %}

{% block content %}
{% endblock %}
    </div>

{% block footer %}
    <footer class="section section-primary footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <h2>성공회대학교</h2>
                    <p>(152-716) 서울특별시 구로구 연동로 320
                        <br>Tel 02)2610-4808 &nbsp; &nbsp; &nbsp; Fax 02)2610-4737
                        <br>Copyright(c) SUNGKONGHOE University. All Right Reserved.
                        <br> * 관리자 / 010-5032-9325 / team.kimkongko@gmail.com</p>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}
</body>
</html>

skhualumni/templates/home.html
{% extends "base.html" %}

{% block title %}홈 화면{% endblock %}

{% load staticfiles %}
{% block content %}

<!-- 메인 숲 사진 -->
<div class="cover">
    <div class="cover-image">
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <h1>성공회대학교 인문학습원
                    <br>
                </h1>
                <p>환영합니다</p>
                <br>
                <br>
            </div>
        </div>
    </div>
</div>

<!-- 공지사항 / 자유게시판 프리뷰 -->
<div class="section">
      <div class="container">
        <ul class="row">
          <div class="section_ul; col-md-6">
            <h2>공지사항</h2>
            <ul>
              <li>
                <span class="bu">›</span>
                <a href="#">12월 공지사항</a>
                <span class="time">2016.12.01</span>
              </li>
              <li>
                <span class="bu">›</span>
                <a href="#">09월 공지사항</a>
                <span class="time">2016.09.24</span>
              </li>
              <li>
                <span class="bu">›</span>
                <a href="#">07월 공지사항</a>
                <span class="time">2016.06.04</span>
              </li>
              <li>
                <span class="bu">›</span>
                <a href="#">06월 공지사항</a>
                <span class="time">2016.06.08</span>
              </li>
              <li>
                <span class="bu">›</span>
                <a href="#">03월 공지사항</a>
                <span class="time">2016.03.02</span>
              </li>
            </ul>
            <a href="#" class="more"><span>›</span>더보기</a>
          </div>
          <class="section_ul; col-md-6">
            <h2>자유게시판</h2>
                <ul>
                    {% for post in post_list %}
                        <li>
                            <span class="bu">›</span>
                            <a href="{% url "board:post_detail" post.pk %}">{{ post.title }}</a>
                            <span class="time">{{ post.created_at }}</span>
                        </li>
                    {% endfor %}
                </ul>
            <a href="{% url "board:index" %}" class="more"><span>›</span>더보기</a>
          </div>
        </div>
      </div>
    </div>

{% endblock %}