skhualumni/board/urls.py
# coding=utf-8
from django.conf.urls import url
from board.views import *

urlpatterns = [
    url(r'^$', index, name='index'),    # 글 목록
    url(r'^(?P<pk>\d+)/$', post_detail, name='post_detail'),    # 글 내용
    url(r'^(?P<pk>\d+)/edit/$', post_edit, name='post_edit'),   # 글 수정
    url(r'^new/$', post_new, name='post_new'),     # 새 글 등록
    url(r'^search/$', PostSearch.as_view(), name='post_search'),  # 글 검색
    url(r'^(?P<pk>\d+)/delete/$', post_delete, name='post_delete'),  # 글 삭제
    url(r'^(?P<pk>\d+)/comments/new/$', comment_new, name='comment_new'),    # 댓글 작성
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/edit/$', comment_edit, name='comment_edit'),     # 댓글 수정
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/delete/$', comment_delete, name='comment_delete'),  # 댓글 삭제
]

skhualumni/info/urls.py
from django.conf.urls import url
from info.views import *

urlpatterns = [
    url(r'^$', render_greeting, name='index'),
    url(r'^greeting/$', render_greeting, name='greeting'),
    url(r'^business/$', render_business, name='business'),
    url(r'^organization/$', render_organization, name='organization'),
    url(r'^map/$', render_map, name='map'),
    url(r'^usage/$', render_usage, name='usage'),
]

skhualumni/skhualumni/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from skhualumni.views import HomeView, UserUpdateView
from skhualumni.forms import CustomPasswordChangeForm
from django.contrib.auth.views import password_change

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    # login, logout, password_change
    url(r'^password_change/$', password_change,
        {'password_change_form': CustomPasswordChangeForm}, name="password_change"),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^my_page/$', UserUpdateView.as_view(), name='my_page'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'^notice/', include('notice.urls', namespace='notice')),
    url(r'^alumni/', include('alumni.urls', namespace='alumni')),
    url(r'^info/', include('info.urls', namespace='info')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skhualumni/board/models.py
# coding=utf-8
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings


class Post(models.Model):
    title = models.CharField(max_length=50)
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(max_length=10000)
    photo = models.ImageField(blank=True, null=True, upload_to='FreeBoard/%Y/%m/%d')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "게시글"
        verbose_name_plural = "게시글"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('board:post_detail', args=(self.pk,))

    def delete(self, *args, **kwargs):
        self.photo.delete()
        super(Post, self).delete(*args, **kwargs)


class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "댓글"
        verbose_name_plural = "댓글"

skhualumni/alumni/views.py
# coding=utf-8
from django.views.generic import ListView, DetailView
from alumni.models import User


class UserSearchMixin(object):

    def get_queryset(self):
        # 부모의 get_queryset으로 부터 queryset을 가져옵니다.
        queryset = super(UserSearchMixin, self).get_queryset()

        # q라는 파라미터를 가져옵니다.
        q = self.request.GET.get("q")
        if q:
            # q가 이름에 포함되거나 핸드폰번호를 공개한 사람의 핸드폰 번호에 포함되면 결과를 냅니다.
            q1 = queryset.filter(name__icontains=q)
            q2 = queryset.filter(login_id__icontains=q)
            q2 = q2.exclude(open_login_id=False)
            q3 = queryset.filter(period=q)
            queryset = q1 | q2 | q3
        return queryset


class UserLV(UserSearchMixin, ListView):
    model = User
    queryset = User.objects.filter(is_admin=False)
    ordering = ["-period", ]


class ExecutiveLV(UserLV):
    queryset = User.objects.filter(is_admin=False)
    queryset = queryset.exclude(position='일반회원')


class UserDV(DetailView):
    model = User
    context_object_name = 'alumni'

skhualumni/board/views.py
# coding=utf-8
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import FormView
from django.db.models import Q
from .models import Post, Comment
from .forms import CommentForm, PostEditForm, PostSearchForm
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


@login_required
def index(request):
    post_list = Post.objects.order_by('-id')

    paginator = Paginator(post_list, 10)

    page = request.GET.get('page')
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.page(paginator.num_pages)

    return render(request, 'board/index.html',
                  {'post_list': post_list, })


# 글 검색
class PostSearch(FormView):
    form_class = PostSearchForm
    template_name = 'board/post_search.html'

    def form_valid(self, form):
        sch_word = '%s' % self.request.POST['search_word']
        post_list = Post.objects.filter(Q(title__icontains=sch_word) |
                                        Q(content__icontains=sch_word)).distinct
        context = {'form': form, 'search_term': sch_word, 'object_list': post_list}
        return render(self.request, self.template_name, context)  # No Redirection


# 포스트 보기
@login_required
def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    return render(request, 'board/post_detail.html', {'post': post, })


# 글 수정
@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostEditForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('board:post_detail', pk=post.pk)
    else:
        form = PostEditForm(instance=post)
    return render(request, 'board/post_new.html', {'form': form, })


# 글 삭제
@login_required
def post_delete(request, pk):
    post = Post.objects.get(pk=pk)
    post.delete()

    return redirect('board:index')


# 새글 작성
@login_required
def post_new(request):
    if request.method == "POST":
        form = PostEditForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.writer = request.user
            post.save()
            return redirect('board:post_detail', pk=post.pk)
    else:
        form = PostEditForm()
    return render(request, 'board/post_new.html', {'form': form, })


# 댓글 생성
@login_required
def comment_new(request, pk):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = Post.objects.get(pk=pk)
            comment.save()
            return redirect('board:post_detail', pk)
    else:
        form = CommentForm()
    return render(request, 'board/post_form.html', {'form': form, })


# 댓글 수정
@login_required
def comment_edit(request, post_pk, pk):
    comment = Comment.objects.get(pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = Post.objects.get(pk=post_pk)
            comment.save()
            return redirect('board:post_detail', post_pk)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'board/post_form.html', {'form': form, })


# 댓글 삭제
@login_required
def comment_delete(request, post_pk, pk):
    comment = Comment.objects.get(pk=pk)
    comment.delete()

    return redirect('board:post_detail', post_pk)

skhualumni/board/templates/board/index.html
{% extends "base.html" %}

{% block title %}자유게시판{% endblock %}

{% block content %}
    <div id="content">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <content>
                        <h1>자유게시판</h1>
                        <div class="section">
                            <div class="container">
                                <table cellspacing="0" border="1" summary="게시판의 글제목 리스트" class="tbl_type">
                                    <caption>자유 게시판</caption>
                                    <colgroup>
                                        <col width="80">
                                        <col>
                                        <col width="115">
                                        <col width="85">
                                        <col width="60">
                                    </colgroup>
                                    <thead>
                                    <tr>
                                        <th scope="col">No</th>
                                        <th scope="col">제목</th>
                                        <th scope="col">작성자</th>
                                        <th scope="col">작성일</th>
                                        <th scope="col">조회수</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for post in post_list %}
                                        <tr>
                                            <td class="num">{{ post.pk }}</td>
                                            <td class="title">
                                                <a href="{% url "board:post_detail" post.pk %}">{{ post.title }}</a>
                                            </td>
                                            <td>
                                                {{ post.writer }}
                                            </td>
                                            <td class="date">{{ post.created_at }}</td>
                                            <td class="hit">아직 구현 안함</td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>
                                </table>
                                <div class="col-md-12">
                                    <ul class="pager" style="position:center">
                                    <span class="step-links">
                                        {% if post_list.has_previous %}
                                            <a class="btn btn-primary" href="?page={{ post_list.previous_page_number }}">이전</a>
                                        {% endif %}

                                        <span class="current">
                                            Page <a href="?page={{ post_list.number }}">{{ post_list.number }}</a> of
                                        <a href="?page={{ post_list.paginator.num_pages }}">{{ post_list.paginator.num_pages }}</a>
                                    </span>

                                    <a href="?page=">{{ post_list.Paginator.count }}</a>
                                        {% if post_list.has_next %}
                                            <a class="btn btn-primary" href="?page={{ post_list.next_page_number }}">다음</a>
                                        {% endif %}
                                    </span>

                                    </ul>
                                </div>
                                    <ul style="float:right">
                                        <a class="btn btn-lg btn-primary" href="{% url 'board:post_new' %}">글쓰기</a>
                                    </ul>
                            </div>
                        </div>
                    </content>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

skhualumni/board/templates/board/post_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="section">
        <div class="container">
            <h1>자유게시판</h1>
            <table cellspacing="0" border="1" summary="글 내용을 표시" class="tbl_type">
                <caption>글 읽기</caption>
                <colgroup>
                    <col width="80"><col><col width="80">
                    <col width="150"><col width="80"><col width="150">
                </colgroup>
                <thead>
                <tr>
                    <th scope="row">제목</th>
                    <td colspan="5">{{ post.title }}</td>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <th scope="row">작성자</th>
                    <td> {{ post.writer }}</td>
                    <th scope="row">작성일</th>
                    <td> {{ post.created_at }} </td>
                    <th scope="row">조회</th>
                    <td>1234</td>
                </tr>
                <tr>
                    <td colspan="6" class="cont">
                        <div>
                            {% if post.photo %}
                                <img src="{{ post.photo.url}}" />
                            {% endif%}
                        </div>
                        <span> {{ post.content | linebreaksbr }} </span>
                    </td>
                </tr>
                </tbody>
            </table>
            <a class="btn btn-default" href="{% url "board:index" %}">목록으로</a>
            <a class="btn btn-default" href="{% url "board:post_edit" post.pk %}">수정</a>
            <a class="btn btn-default" href="{% url "board:post_delete" post.pk %}">삭제</a>
            <table>
                {% for comment in post.comment_set.all %}
                    <tr>
                        <td> {{ comment.author }}  | </td>
                        <td> {{ comment.message }}  | </td>
                        <td> {{ comment.created_at }} </td>
                        <td> <a class="btn btn-default" href="{% url "board:comment_edit" post.pk comment.pk %}" >수정</a> </td>
                        <td> <a class="btn btn-default" href="{% url "board:comment_delete" post.pk comment.pk %}" >삭제</a> </td>
                    </tr>
                {% endfor %}
            </table>
            <a class="btn btn-default" href="{% url "board:comment_new" post.pk %}">댓글 작성</a>
        </div>
    </div>

{% endblock %}

skhualumni/board/templates/board/post_form.html
{% extends "base.html" %}

{% block content %}
    <div class="container">
        <form action="" method="POST">
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>

            <input type="submit"/>
        </form>
    </div>
{% endblock %}

skhualumni/board/templates/board/post_new.html
{% extends "base.html" %}

{% block content %}
    <h1>새 게시물 등록</h1>
    <form method="POST" class="post-form" enctype="multipart/form-data">

        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

skhualumni/board/templates/board/post_search.html
{% extends "base.html" %}
{% block title %}post_search.html{% endblock %}

{% block content %}
    <h1>자유게시판 검색</h1>
    <form action="." method="post"> {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Submit" />
    </form>

    <br/><br/>

    {% if object_list %}
        {% for post in object_list %}
            <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            {{ post.modify_date|date:"N d, Y" }}
            <p>{{ post.description }}</p>
        {% endfor %}

    {% elif search_term %}
        <b><i>검색하신 단어 ({{ search_term }}) 가 없습니다.</i></b>
    {% endif %}

{% endblock %}