skhualumni/alumni/urls.py
from django.conf.urls import url
from alumni.views import UserLV, ExecutiveLV, UserDV

urlpatterns = [
    url(r'^$', UserLV.as_view(), name='index'),
    url(r'^executive/$', ExecutiveLV.as_view(), name='executive'),
    url(r'^(?P<pk>\d+)/$', UserDV.as_view(), name='detail'),
]

skhualumni/info/urls.py
from django.conf.urls import url
from info.views import *

urlpatterns = [
    url(r'^$', render_greeting, name='index'),
    url(r'^greeting/$', render_greeting, name='greeting'),
    url(r'^business/$', render_business, name='business'),
    url(r'^organization/$', render_organization, name='organization'),
    url(r'^map/$', render_map, name='map'),
    url(r'^usage/$', render_usage, name='usage'),
]

skhualumni/skhualumni/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from skhualumni.views import HomeView, UserUpdateView
from skhualumni.forms import CustomPasswordChangeForm
from django.contrib.auth.views import password_change

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    # login, logout, password_change
    url(r'^password_change/$', password_change,
        {'password_change_form': CustomPasswordChangeForm}, name="password_change"),
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^my_page/$', UserUpdateView.as_view(), name='my_page'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^board/', include('board.urls', namespace='board')),
    url(r'^notice/', include('notice.urls', namespace='notice')),
    url(r'^alumni/', include('alumni.urls', namespace='alumni')),
    url(r'^info/', include('info.urls', namespace='info')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

skhualumni/alumni/models.py
# coding=utf-8
# for python 2
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible

from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser,
    PermissionsMixin)


class UserManager(BaseUserManager):
    def create_user(self, login_id, name, period, email, password=None):
        if not login_id:
            raise ValueError('Users must have a login_id')

        user = self.model(
            login_id=login_id,
            name=name,
            period=period,
            email=UserManager.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, login_id, name, period, email, password):
        u = self.create_user(login_id=login_id,
                             name=name,
                             period=period,
                             email=email,
                             password=password,
                             )
        u.is_admin = True
        u.save(using=self._db)
        return u


@python_2_unicode_compatible
class User(AbstractBaseUser, PermissionsMixin):
    login_id = models.CharField('ID', max_length=11, unique=True)
    name = models.CharField('이름', max_length=10, blank=False)
    email = models.EmailField('Email', max_length=255, unique=True)
    birth = models.DateField('생일', null=True)
    period = models.IntegerField('기수', blank=True, default=0)
    position = models.CharField('동문회 직책', max_length=15, default="일반회원")
    position_all = models.CharField('총 동문회 직책', max_length=15, blank=True)
    picture = models.ImageField('프로필 사진', blank=True, upload_to='user_picture')
    work = models.CharField('직장', max_length=45, blank=True)
    work_phone = models.CharField('직장 전화', max_length=14, blank=True)
    work_position = models.CharField('직장 직위', max_length=45, blank=True)
    create_date = models.DateTimeField('가입일', auto_now_add=True)
    last_login = models.DateTimeField('마지막 로그인', auto_now=True, blank=True)
    is_active = models.BooleanField('사용여부', default=True)
    is_admin = models.BooleanField('관리자', default=False)
    is_first_login = models.BooleanField('최초로그인여부', default=True)
    # open or not
    open_login_id = models.BooleanField('핸드폰 번호 공개여부', default=False)
    open_email = models.BooleanField('이메일 공개여부', default=False)
    open_picture = models.BooleanField('프로필 사진 공개여부', default=False)
    open_work = models.BooleanField('직장 공개여부', default=False)
    open_work_phone = models.BooleanField('직장 전화 공개여부', default=False)
    open_work_position = models.BooleanField('직장 직위 공개여부', default=False)

    objects = UserManager()

    USERNAME_FIELD = 'login_id'
    REQUIRED_FIELDS = ['name', 'period', 'email']

    class Meta:
        verbose_name = "사용자"
        verbose_name_plural = "사용자"

    def get_full_name(self):
        # The user is identified by their email address
        return self.name

    def get_short_name(self):
        # The user is identified by their email address
        return self.name

    def __str__(self):
        return self.name

    def has_perm(self, perm, obj=None):
        # "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        # "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        # "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

skhualumni/alumni/views.py
# coding=utf-8
from django.views.generic import ListView, DetailView
from alumni.models import User


class UserSearchMixin(object):

    def get_queryset(self):
        # 부모의 get_queryset으로 부터 queryset을 가져옵니다.
        queryset = super(UserSearchMixin, self).get_queryset()

        # q라는 파라미터를 가져옵니다.
        q = self.request.GET.get("q")
        if q:
            # q가 이름에 포함되거나 핸드폰번호를 공개한 사람의 핸드폰 번호에 포함되면 결과를 냅니다.
            q1 = queryset.filter(name__icontains=q)
            q2 = queryset.filter(login_id__icontains=q)
            q2 = q2.exclude(open_login_id=False)
            q3 = queryset.filter(period=q)
            queryset = q1 | q2 | q3
        return queryset


class UserLV(UserSearchMixin, ListView):
    model = User
    queryset = User.objects.filter(is_admin=False)
    ordering = ["-period", ]


class ExecutiveLV(UserLV):
    queryset = User.objects.filter(is_admin=False)
    queryset = queryset.exclude(position='일반회원')


class UserDV(DetailView):
    model = User
    context_object_name = 'alumni'

skhualumni/alumni/templates/alumni/_user_search.html
{# templates/alumni/_user_search.html #}
{% comment %}
    Usage: {% include "alumni/_user_search.html" %}
{% endcomment %}
<form action="{% url 'alumni:index' %}" method="GET">
    <input type="text" name="q" />
    <button type="submit">search</button>
</form>

skhualumni/alumni/templates/alumni/user_detail.html
{% extends "base.html" %}

{% block title %}동문 세부{% endblock %}

{% load staticfiles %}
{% block content %}
    <div id="content" class="container">
        <div class="user-picture-detail" style="float:left">
            {% if alumni.open_picture and alumni.picture %}
                <img src="{{ alumni.picture.url }}" />
            {% else %}
                <img src="{% static "/images/etc/unknown.png" %}" />
            {% endif %}
        </div>
        <div class="user-info-detail">
            <li>이름 : {{ alumni }}</li>
            <li>기수 : {{ alumni.period }}기</li>
            {% if alumni.open_email %}
            <li>이메일 : {{ alumni.email }}</li>
            {% endif %}
            {% if alumni.open_login_id %}
            <li>핸드폰번호 : {{ alumni.login_id }}</li>
            {% endif %}
            <li>직책 : {{ alumni.position }}</li>
            {% if alumni.open_login_id %}
            <li>총동문회 직책 : {{ alumni.position_all }}</li>
            {% endif %}
            {% if alumni.open_work and alumni.work %}
            <li>직장 : {{ alumni.work }}</li>
            {% endif %}
            {% if alumni.open_work_phone and alumni.work_phone %}
            <li>직장 전화번호 : {{ alumni.work_phone }}</li>
            {% endif %}
            {% if alumni.open_work_position and alumni.work_position %}
            <li>직장 직위 : {{ alumni.work_position }}</li>
            {% endif %}
        </div>
    </div>
{% endblock %}

skhualumni/alumni/templates/alumni/user_list.html
{% extends "base.html" %}

{% block title %}SKHU 동문 목록{% endblock %}

{% load staticfiles %}
{% block content %}
    <div class="section">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="page-header">
                        {% if request.path == '/alumni/' %}
                            <h1>동문 목록</h1>
                        {% elif request.path == '/alumni/executive/' %}
                            <h1>임원 목록</h1>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div id="user-search">
                {% include "alumni/_user_search.html" %}
            </div>
            {% for user in object_list %}
                {% ifchanged user.period %}
                    <div class="row">
                        <div class="col-md-12">
                            <h2 class="text-center">{{ user.period }}기</h2>
                        </div>
                    </div>
                    <hr style="border: solid black 1px;">
                {% endifchanged %}
                {% if forloop.counter|divisibleby:2 %}
                    <div class="row">
                {% endif %}

            <a href="{% url 'alumni:detail' user.id %}">
                <div class="col-md-2">
                    {% if user.open_picture and user.picture %}
                        <img class="img-circle img-responsive" src="{{ user.picture.url }}" />
                    {% else %}
                        <img class="img-circle img-responsive" src="{% static "images/etc/unknown.png" %}" />
                    {% endif %}
                </div>
            </a>
            <div class="col-md-4">
                <h3 class="text-left">{{ user }}</h3>
                <p class="text-left">{{ user.period }}기 / {{ user.position }}</p>
                {% if user.open_login_id %}
                    <p class="text-left">
                    <a href="tel:{{ user.login_id }}">{{ user.login_id }}</a>
                {% endif %}
                {% if user.open_email %}
                    <p class="text-left">
                        <a href="mailto:{{ user.email }}">{{ user.email }}</a>
                    </p>
                {% endif %}
            </div>
            {% if forloop.counter|divisibleby:2 %}
                </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}